# Generated by Django 3.1b1 on 2020-11-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowOnSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('facebookpage', models.CharField(max_length=200)),
                ('instagramhandle', models.CharField(max_length=200)),
                ('youtubepage', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
            ],
        ),
    ]
