# Generated by Django 3.1b1 on 2020-11-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='other',
            old_name='list',
            new_name='overview',
        ),
    ]
