# Generated by Django 3.1b1 on 2020-11-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201127_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_service',
            name='list',
            field=models.CharField(max_length=100),
        ),
    ]
