# Generated by Django 3.1b1 on 2020-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('thumbnail_1', models.ImageField(upload_to='pics')),
                ('thumbnail_2', models.ImageField(upload_to='pics')),
                ('thumbnail_3', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
