# Generated by Django 3.1b1 on 2020-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_photo',
            name='overview',
            field=models.CharField(max_length=100),
        ),
    ]
