# Generated by Django 3.1b1 on 2020-11-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201128_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_photo',
            old_name='overview',
            new_name='title',
        ),
    ]
