# Generated by Django 3.1b1 on 2020-11-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='featured',
        ),
    ]
